import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Table from './components/Table/Table'
import DataJson from './components/Table/DataMock.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {columns, data} = DataJson
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Table&nbsp;
            <code className={styles.code}>components/Table/Table.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> 
              </a>
          </div>
        </div>

        <div className={styles.center}>
          <Table columns={columns} data={data} multipleSelecion={true}></Table> 
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            Hugo <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Find in-depth information about Next.js features and&nbsp;API. */}
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Learn about Next.js in an interactive course with&nbsp;quizzes! */}
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Notion <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Discover and deploy boilerplate example Next.js&nbsp;projects. */}
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              {/* Instantly deploy your Next.js site to a shareable URL */}
              {/* with&nbsp;Vercel. */}
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
